from django.urls import path
from . import views

urlpatterns = [
    path('stats/bad-operations/', views.statistics_bad_operations, name='statistics_bad_operations'),
    path('stats/operations-planning/', views.operations_planning, name='operations_planning'),
    path('warehouse/update-location/', views.update_storage_location, name='update_storage_location'),
    path('warehouse/bulk-issue/', views.warehouse_bulk_issue, name='warehouse_bulk_issue'),
    path('order/<int:order_id>/material-report/', views.order_material_report, name='order_material_report'),
    path('warehouse/print-report/', views.warehouse_print_report, name='warehouse_print_report'),
    path('warehouse/report/', views.warehouse_report, name='warehouse_report'),
    path('order/<int:order_id>/tree/export/', views.order_tree_export, name='order_tree_export'),
    path('order/<int:order_id>/colors/', views.save_order_colors, name='save_order_colors'),
    path('order/<int:order_id>/download-all-ml/', views.download_all_route_cards, name='download_all_ml'),
    path('order/<int:order_id>/due-date/', views.update_order_due_date, name='update_order_due_date'),
    path('order/<int:order_id>/status/<str:new_status>/', views.change_order_status, name='change_order_status'),
    path('orders-control/', views.orders_control, name='orders_control'),
    path('search/', views.search, name='search'),
    path('restore/', views.restore_backup, name='restore_backup'),
    path('order/create/', views.order_create, name='order_create'),
    path('stats/compare/', views.statistics_compare, name='stats_compare'),
    path('stats/export/', views.statistics_export, name='stats_export'),
    path('stats/operations/<str:type_name>/export/', views.statistics_operations_export, name='stats_operations_export'),
    path('stats/operations/<str:type_name>/', views.statistics_operations, name='stats_operations'),
    path('stats/', views.statistics, name='stats'),
    path('', views.dashboard, name='home'),
    path('orders/', views.order_list, name='order_list'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/<int:order_id>/tree/', views.order_tree, name='order_tree'),
    path('order/<int:order_id>/import/', views.order_import, name='order_import'),
    path('instance/<str:item_number>/<str:serial>/', views.instance_detail, name='instance_detail'),
    path('supplement/<int:instance_id>/', views.supplement_instance, name='supplement_instance'),
    path('route-card/<int:route_card_id>/print/', views.route_card_print, name='route_card_print'),
    path('route-card/<int:route_card_id>/export/', views.route_card_export, name='route_card_export'),
    path('route-card/create/<int:instance_id>/', views.route_card_create, name='route_card_create'),

    path('warehouse/', views.warehouse_dashboard, name='warehouse'),
    path('warehouse/issue/', views.warehouse_issue, name='warehouse_issue'),
]
