# Generated by Django 6.0.4 on 2026-05-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_iteminstance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='Деталь', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='routecard',
            name='instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_card', to='scanner.iteminstance', verbose_name='Экземпляр'),
        ),
    ]
