# Generated by Django 6.0.4 on 2026-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_item_item_number_alter_item_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Рабочий'), ('technologist', 'Технолог'), ('controller', 'Контролёр'), ('storekeeper', 'Кладовщик')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
