# Generated by Django 6.0.4 on 2026-05-02 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Марка')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код')),
                ('profile', models.CharField(blank=True, max_length=200, verbose_name='Профиль/сортамент')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='ГОСТ/ОСТ')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='Плотность')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('paused', 'Приостановлен'), ('completed', 'Завершён'), ('shipped', 'Отгружен'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='bad_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Брак'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='good_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Годных'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.operationtype', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Норма часов'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='route_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='scanner.routecard', verbose_name='Маршрутная карта'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='routeoperation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.material', verbose_name='Материал'),
        ),
    ]
