# Generated by Django 6.0.4 on 2026-05-02 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_material_alter_iteminstance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('recipient', models.CharField(blank=True, max_length=200, verbose_name='Получатель')),
                ('basis', models.CharField(blank=True, max_length=300, verbose_name='Основание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.employee', verbose_name='Сотрудник')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_records', to='scanner.iteminstance', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Складская запись',
                'verbose_name_plural': 'Складские записи',
            },
        ),
    ]
