# Generated by Django 6.0.4 on 2026-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_warehouserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Рабочий'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер'), ('controller', 'Контролёр'), ('storekeeper', 'Кладовщик')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
