# Generated by Django 6.0.4 on 2026-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки'),
        ),
        migrations.AddField(
            model_name='item',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок на партию'),
        ),
    ]
