# Generated by Django 6.0.4 on 2026-05-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_item_blank_size_item_blanks_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profile',
            field=models.CharField(blank=True, max_length=200, verbose_name='Профиль/сортамент'),
        ),
        migrations.AlterField(
            model_name='item',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок'),
        ),
    ]
