# Generated by Django 6.0.4 on 2026-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_item_profile_alter_item_blanks_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
