# Generated by Django 6.0.4 on 2026-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_iteminstance_due_date_order_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Полное наименование'),
        ),
    ]
