# Generated by Django 6.0.4 on 2026-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_alter_order_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Номер договора'),
        ),
    ]
