# Generated by Django 6.0.4 on 2026-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color1',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='color2',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет 2'),
        ),
    ]
