# Generated by Django 6.0.4 on 2026-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_order_color1_order_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserecord',
            name='setup_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Настроечные'),
        ),
        migrations.AlterField(
            model_name='warehouserecord',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='План на сборку'),
        ),
    ]
