# Generated by Django 6.0.4 on 2026-06-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_warehouserecord_setup_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouserecord',
            name='setup_quantity',
        ),
    ]
