# Generated by Django 6.0.4 on 2026-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_remove_warehouserecord_setup_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='План на сборку'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='План на сборку'),
        ),
    ]
