# Generated by Django 6.0.4 on 2026-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_alter_iteminstance_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='blank_size',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Размер заготовки (экз.)'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='blanks_per_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во заготовок (экз.)'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='setup_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Настроечные'),
        ),
    ]
