# Generated by Django 6.0.4 on 2026-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_alter_iteminstance_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='blank_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='blanks_per_item',
        ),
        migrations.RemoveField(
            model_name='material',
            name='profile',
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='setup_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Настроечные'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='setup_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Настроечные'),
        ),
    ]
