# Generated by Django 6.0.4 on 2026-06-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_iteminstance_blank_size_iteminstance_blanks_per_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create_order', 'Создание заказа'), ('edit_order', 'Изменение заказа'), ('delete_order', 'Удаление заказа'), ('complete_operation', 'Завершение операции'), ('start_operation', 'Начало операции'), ('issue_warehouse', 'Выдача со склада'), ('change_location', 'Изменение места хранения'), ('import_spec', 'Загрузка спецификации'), ('supplement', 'Дозапуск'), ('other', 'Прочее')], max_length=30, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
