# Generated by Django 6.0.4 on 2026-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_remove_item_blank_size_remove_item_blanks_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminstance',
            name='blank_size',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='blanks_per_item',
        ),
        migrations.AddField(
            model_name='item',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки'),
        ),
        migrations.AddField(
            model_name='item',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок'),
        ),
    ]
