# Generated by Django 6.0.4 on 2026-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='Проект'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
