# Generated by Django 6.0.4 on 2026-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_remove_iteminstance_blank_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки (экз.)'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок (экз.)'),
        ),
        migrations.AddField(
            model_name='material',
            name='profile',
            field=models.CharField(blank=True, max_length=200, verbose_name='Профиль/сортамент'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='blank_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Размер заготовки (экз.)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='blanks_per_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во заготовок (экз.)'),
        ),
    ]
