# Generated by Django 6.0.4 on 2026-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_iteminstance_project_order_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoperation',
            name='worker_log',
            field=models.TextField(blank=True, verbose_name='История исполнителей'),
        ),
    ]
