# Generated by Django 6.0.4 on 2026-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_iteminstance_blank_size_iteminstance_blanks_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='setup_quantity',
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='blanks_per_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во заготовок (экз.)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='blanks_per_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во заготовок (экз.)'),
        ),
    ]
