# Generated by Django 6.0.4 on 2026-06-24 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_routeoperation_worker_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('good_qty', models.PositiveIntegerField(default=0, verbose_name='Годных')),
                ('bad_qty', models.PositiveIntegerField(default=0, verbose_name='Брак')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.routeoperation', verbose_name='Операция')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Запись выполнения',
                'verbose_name_plural': 'Журнал выполнения операций',
                'ordering': ['started_at'],
            },
        ),
    ]
