# Generated by Django 6.0.4 on 2026-06-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_remove_orderitem_setup_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='blank_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='blanks_per_item',
        ),
    ]
