# Generated by Django 6.0.4 on 2026-07-23 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0023_operationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает закупки'), ('invoice', 'Счёт в оплате'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('received', 'Принят на склад'), ('issued', 'Выдан со склада')], default='pending', max_length=20, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.item', verbose_name='Изделие'),
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Выдача')], max_length=3)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('basis', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to='scanner.orderitem')),
            ],
            options={
                'verbose_name': 'Движение покупного изделия',
                'verbose_name_plural': 'Движения покупных изделий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OperationLog',
        ),
    ]
