# Generated by Django 6.0.4 on 2026-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0024_orderitem_purchase_status_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Наименование'),
        ),
    ]
