# Generated by Django 6.0.4 on 2026-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0025_orderitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assembly_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сборка'),
        ),
    ]
