# Generated by Django 6.0.4 on 2026-07-29 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0026_orderitem_assembly_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='purchase_status',
        ),
        migrations.RemoveField(
            model_name='purchasetransaction',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scanner.item', verbose_name='Изделие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='basis',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Основание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Получатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Выдача')], max_length=3, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('designation', models.CharField(blank=True, max_length=300, verbose_name='Обозначение')),
                ('assembly_name', models.CharField(blank=True, max_length=500, verbose_name='Подсборка (название)')),
                ('quantity_required', models.PositiveIntegerField(default=0, verbose_name='Требуемое количество')),
                ('quantity_purchased', models.PositiveIntegerField(default=0, verbose_name='Закупленное количество')),
                ('purchase_status', models.CharField(choices=[('pending', 'Ожидает закупки'), ('invoice', 'Счёт в оплате'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('received', 'Принят на склад'), ('issued', 'Выдан')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_refs', to='scanner.orderitem', verbose_name='Подсборка (ссылка)')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='scanner.order')),
            ],
            options={
                'verbose_name': 'Покупное изделие',
                'verbose_name_plural': 'Покупные изделия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='purchase_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='scanner.purchaseitem'),
            preserve_default=False,
        ),
    ]
