# Generated by Django 6.0.4 on 2026-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0027_remove_orderitem_assembly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_status',
            field=models.CharField(choices=[('pending', 'Ожидает закупки'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('incoming_inspection', 'Прошел входной контроль'), ('galvanika', 'Гальваника'), ('ready_for_issue', 'Готов к выдаче'), ('issued', 'Выдан')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
