# Generated by Django 6.0.4 on 2026-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0028_alter_purchaseitem_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='batch_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Токен группы'),
        ),
    ]
