# Generated by Django 6.0.4 on 2026-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0029_purchasetransaction_batch_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Рабочий'), ('supervisor', 'Руководитель'), ('technologist', 'Технолог'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер'), ('controller', 'Контролёр'), ('storekeeper', 'Кладовщик'), ('purchase_storekeeper', 'Кладовщик стандартных изделий')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
