# Generated by Django 6.0.4 on 2026-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0030_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_status',
            field=models.CharField(choices=[('pending', 'Ожидает закупки'), ('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('received_warehouse', 'Получено на склад'), ('sent_to_inspection', 'Передано на входной контроль'), ('incoming_inspection', 'Прошел входной контроль'), ('galvanika', 'Гальваника'), ('ready_for_issue', 'Готов к выдаче'), ('issued', 'Выдан')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
