# Generated by Django 6.0.4 on 2026-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0031_alter_purchaseitem_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание (общее для заказа)'),
        ),
    ]
