# Generated by Django 6.0.4 on 2026-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0032_purchaseitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Выдано'),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Выдано'),
        ),
    ]
